from pydantic import BaseModel, Field, validator
from typing import Optional
from bson.objectid import ObjectId


class DataChunk(BaseModel):
    id: Optional[ObjectId] = Field(None, alias="_id") # MongoDB will automatically generate an ObjectId for this field as a bson ObjectId type
    chunk_text: str = Field(..., min_length=1,description="The text content of the data chunk")
    chunk_metadata: dict = Field(..., description="Metadata associated with the data chunk, such as source file, position in the file, etc.")
    chunk_order: int = Field(...,gt=0, description="The order of the chunk in the original file, starting from 0 for the first chunk")
    chunk_project_id: ObjectId
    chunk_asset_id: ObjectId

    class Config:
        arbitrary_types_allowed = True # Allow ObjectId type to be used in the model
        # This is necessary to allow the use of ObjectId type for the _id field, which is generated by MongoDB and is not a standard Python type.

    @classmethod
    def get_indexes(cls): # Define the indexes for the collection
        return [
            {
                "key": [ # Create an index on the chunk_project_id field to improve query performance when retrieving chunks by project_id
                    ("chunk_project_id", 1)
                ],
                "name": "chunk_project_id_index_1",
                "unique": False #Allow multiple chunks to have the same chunk_project_id, as they belong to the same project
               }
            ]