from pydantic import BaseModel, Field, validator
from typing import Optional
from bson.objectid import ObjectId


class DataChunk(BaseModel):
    _id: Optional[ObjectId] # MongoDB will automatically generate an ObjectId for this field as a bson ObjectId type
    chunk_text: str = Field(..., min_length=1,description="The text content of the data chunk")
    chunk_metadata: dict = Field(..., description="Metadata associated with the data chunk, such as source file, position in the file, etc.")
    chunk_order: int = Field(...,gt=0, description="The order of the chunk in the original file, starting from 0 for the first chunk")
    chunk_project_id: ObjectId

    class Config:
        arbitrary_types_allowed = True # Allow ObjectId type to be used in the model
        # This is necessary to allow the use of ObjectId type for the _id field, which is generated by MongoDB and is not a standard Python type.