from pydantic import BaseModel, Field, validator
from typing import Optional
from bson.objectid import ObjectId

class Project(BaseModel):
    _id: Optional[ObjectId] # MongoDB will automatically generate an ObjectId for this field as a bson ObjectId type 
    project_id: str = Field(..., min_length=1, max_length=100, description="Unique identifier for the project")
    description: str

    @validator('project_id')
    def validate_project_id(cls, value):
        if not value.isalnum(): # Ensure the project_id is alphanumeric
            raise ValueError('project_id must be alphanumeric')
        return value
    
    class Config:
        arbitrary_types_allowed = True # Allow ObjectId type to be used in the model
        # This is necessary to allow the use of ObjectId type for the _id field, which is generated by MongoDB and is not a standard Python type.